### ISSUE TITLE
Cipher names don't match standard names

### ISSUE THREAD

**Issue by 7--** [noxxi/p5-ssl-tools#13]
When I run the script on a endpoint im trying to connect to I get:
```
supported ciphers with SSLv23 handshake
   * TLSv1_2 AES128-GCM-SHA256
   * TLSv1_2 AES256-GCM-SHA384
   * TLSv1_2 AES128-SHA256
   * TLSv1_2 AES256-SHA256
   * TLSv1_2 ECDHE-RSA-AES128-GCM-SHA256
   * TLSv1_2 ECDHE-RSA-AES256-GCM-SHA384
   * TLSv1_2 ECDHE-RSA-AES128-SHA256
   * TLSv1_2 ECDHE-RSA-AES256-SHA384
```
These cipher suite names don't match the standard exactly. I don't know enough to say which of the cipher suites supports my client. How am I suppose to know which ones I can use?

These are the ciphers my client (Websphere 8.5) supports: 
SSL_RSA_WITH_RC4_128_MD5
SSL_RSA_WITH_RC4_128_SHA
SSL_RSA_WITH_AES_128_CBC_SHA
SSL_DHE_RSA_WITH_AES_128_CBC_SHA
SSL_DHE_DSS_WITH_AES_128_CBC_SHA
SSL_RSA_WITH_3DES_EDE_CBC_SHA 
SSL_RSA_FIPS_WITH_3DES_EDE_CBC_SHA
SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA 
SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA
SSL_DHE_DSS_WITH_RC4_128_SHA
SSL_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
SSL_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
SSL_ECDHE_RSA_WITH_AES_128_GCM_SHA256
SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA256
SSL_RSA_WITH_AES_128_GCM_SHA256
SSL_RSA_WITH_AES_128_CBC_SHA256
SSL_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
SSL_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
SSL_ECDH_RSA_WITH_AES_128_GCM_SHA256 
SSL_ECDH_RSA_WITH_AES_128_CBC_SHA256
SSL_DHE_RSA_WITH_AES_128_GCM_SHA256
SSL_DHE_RSA_WITH_AES_128_CBC_SHA256 
SSL_DHE_DSS_WITH_AES_128_GCM_SHA256
SSL_DHE_DSS_WITH_AES_128_CBC_SHA256
SSL_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA
SSL_ECDH_ECDSA_WITH_AES_128_CBC_SHA
SSL_ECDH_RSA_WITH_AES_128_CBC_SHA
SSL_ECDHE_ECDSA_WITH_RC4_128_SHA
SSL_ECDHE_RSA_WITH_RC4_128_SHA
SSL_ECDH_ECDSA_WITH_RC4_128_SHA
SSL_ECDH_RSA_WITH_RC4_128_SHA
SSL_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
SSL_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
SSL_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
SSL_ECDH_RSA_WITH_3DES_EDE_CBC_SHA 

These names aren't exactly right either should start with TLS instead of SSL.

The standard cipher suite names are defined here: 
https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4

**Comment by noxxi** [comment]
These are the names used by OpenSSL. For a mapping between the OpenSSL syntax and the syntax you'll find in RFC see [man ciphers](https://www.openssl.org/docs/manmaster/man1/ciphers.html).

**Comment by 7--** [comment]
Thank you sir
